### PR TITLE
Python3 compatibility, optimisations and face box cropping on and off 

### PR DESCRIPTION
**Pull request by bendog**

### CODE REVIEW

**Comment by wobeng** [comment]
you are the man...will test this and merge.
Thanks

**Comment by bendog** [comment]
I haven't tested this running as a lambda yet, so I'm not sure if the packages need to be compiled from source, I'm assuming they don't.

**Comment by bendog** [comment]
I wasn't sure why the requirements.txt was pointing to a personal repo, so I removed that, is that ok?

**Comment by wobeng** [comment]
I will test it and update the packages. 

Yes, it's okay to remove my personal package. The changes I made in Zappa https://github.com/Miserlou/Zappa/blob/5e04ed4a93472d3e2633798c5bb8f972bbf17f2e/CHANGELOG.md#0360 to accommodate this app has been merged with the Zappa, so no need.

**Pull request merged**
